<a href="https://colab.research.google.com/github/Julianamihailova/laba/blob/main/lab3/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 3

##Обработка пропущенных значений

Обработайте пропущенные значения:


* Удалите пропущенные значения
* Заполните при помощи медианы, среднего для числовых значений
* Заполните при помощи моды для категориальных значений
* Интерполируйте
Выведите статистку после каждого метода и объясните

In [11]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

In [14]:
import pandas as pd

df = pd.read_csv('/content/shanghaiData.csv')
df

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,NaN,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,NaN,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,NaN,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,NaN,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,NaN,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [15]:
df_cleaned = df.dropna()
df_cleaned

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4492,96,McMaster University,4,24.4,12.6,18.8,23.2,15.1,44.5,22.5,2015
4493,97,University of Bonn,4,24.3,15.4,19.8,17.4,21.1,39.8,25.9,2015
4494,98,VU University Amsterdam,4,24.2,0.0,0.0,27.8,18.0,55.5,33.3,2015
4495,99,Michigan State University,50,24.0,8.9,0.0,30.7,21.8,50.6,18.9,2015
4496,100,Texas A&M University,51,23.9,0.0,0.0,34.3,22.7,49.5,20.9,2015

In [16]:
df_filled_median = df.fillna(df.median())
df_filled_median

<ipython-input-16-2e656cba09d7>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_median = df.fillna(df.median())

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,31.3,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,31.3,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,31.3,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,31.3,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,31.3,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [17]:
df_filled_mean = df.fillna(df.mean())

df_filled_mean

<ipython-input-17-d5c7e4df689e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_mean = df.fillna(df.mean())

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.00000,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.60000,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.40000,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.80000,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.10000,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,36.38347,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,36.38347,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,36.38347,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,36.38347,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,36.38347,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [18]:
df_filled_mode = df.fillna(df["award"].mode()[0])
df_filled_mode

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,0.0,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,0.0,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,0.0,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,0.0,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,0.0,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [19]:
df_interpolated = df.interpolate()

df_interpolated

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,23.9,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,23.9,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,23.9,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,23.9,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,23.9,0.0,0.0,14.9,7.5,25.0,11.9,2015

**Объясните**

##Поиск выбросов и аномалий

**Те, кто выполняет задания со * делают поиск выбросов с помощью написанного ранее класса**

Найти выбросы по числовой переменной (использовать метод основанный на среднем и на межквартильном размахе). Объясните результат

Вывести статистику с выбросами и без. Сравните и объясните результат

In [28]:
#Методом среднего
mean = df["pcp"].mean()
std_deviation = df["pcp"].std()
threshold = 3 * std_deviation

outliers = [x for x in df["pcp"] if abs(x - mean) > threshold]
df["pcp"].describe()

print("Среднее значение данных:", mean)
print("Стандартное отклонение данных:", std_deviation)
print("Потенциальные выбросы:", outliers)

Среднее значение данных: 31.52234332425068
Стандартное отклонение данных: 12.621984080967742
Потенциальные выбросы: [72.4, 100.0, 73.6, 100.0, 73.0, 100.0, 74.1, 100.0, 74.8, 100.0, 100.0, 70.5, 100.0, 71.1, 100.0, 72.5, 100.0, 75.3, 100.0, 76.6, 70.3, 100.0]

In [34]:
#При помощи межквартильного размаха
Q1 =  df["pcp"].quantile(0.25)
Q3 = df["pcp"].quantile(0.75)
IQR = Q3 - Q1
df_IQR = df[(df["pcp"] > (Q1-1.5*IQR )) & (df["pcp"] < (Q3+1.5*IQR))]

df_IQR["pcp"].describe()

print("Интерквантильный размах:", IQR)
print("Межквантильные данные:", df_IQR)

Интерквантильный размах: 9.700000000000003
Межквантильные данные:      world_rank                        university_name national_rank  \
6             7                    Columbia University             6
8             9                  University of Chicago             8
11           12                     Cornell University            10
12           13    University of California, San Diego            11
13           14  University of California, Los Angeles            12
...         ...                                    ...           ...
4492         96                    McMaster University             4
4493         97                     University of Bonn             4
4494         98                VU University Amsterdam             4
4495         99              Michigan State University            50
4496        100                   Texas A&M University            51

      total_score  alumni  award  hici    ns   pub   pcp  year
6            62.3    79.4   60.6  56.1  54.2  69.5  45.4  2005
8            60.1    75.6   81.9  50.3  44.7  56.4  42.2  2005
11           54.6    46.5   52.4  55.0  48.8  66.3  39.8  2005
12           51.0    17.7   34.7  59.8  56.5  64.5  46.6  2005
13           50.6    27.3   32.8  56.7  50.1  75.6  34.3  2005
...           ...     ...    ...   ...   ...   ...   ...   ...
4492         24.4    12.6   18.8  23.2  15.1  44.5  22.5  2015
4493         24.3    15.4   19.8  17.4  21.1  39.8  25.9  2015
4494         24.2     0.0    0.0  27.8  18.0  55.5  33.3  2015
4495         24.0     8.9    0.0  30.7  21.8  50.6  18.9  2015
4496         23.9     0.0    0.0  34.3  22.7  49.5  20.9  2015

[1007 rows x 11 columns]

In [40]:
#Статистика и объяснение
df["pcp"].describe()

count    1101.000000
mean       29.957947
std        12.921263
min        14.800000
25%        22.700000
50%        27.300000
75%        33.300000
max       100.000000
Name: pcp, dtype: float64

**Объяснения**

##Дубликаты

Проверьте датафрейм на дубликаты и удалите их, если дублей нет - создайте.

In [ ]:
df.describe()

,total_score,alumni,award,hici,ns,pub,pcp,year
count,1101.000000,4896.000000,4895.00000,4895.000000,4875.000000,4895.000000,4895.000000,4897.000000
mean,36.383470,9.161724,7.69191,16.221491,16.078503,38.254648,21.242329,2009.658566
std,13.557186,14.140636,15.49411,14.382710,12.511529,13.050809,9.254351,3.197576
min,23.500000,0.000000,0.00000,0.000000,0.000000,7.300000,8.300000,2005.000000
25%,27.400000,0.000000,0.00000,7.300000,8.000000,28.900000,15.600000,2007.000000
50%,31.300000,0.000000,0.00000,12.600000,12.800000,36.000000,19.000000,2009.000000
75%,41.800000,15.600000,13.40000,21.700000,19.800000,45.300000,24.500000,2012.000000
max,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,2015.000000

In [ ]:
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,NaN,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,NaN,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,NaN,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,NaN,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,NaN,0.0,0.0,14.9,7.5,25.0,11.9,2015

## Преобразование признаков

Масштабируйте числовые признаки через MinMaxScaler, StandardScaler

In [44]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

num_features = df.select_dtypes(include=['float64']).columns

num_features
df.pcp.unique()
scaler_minmax = MinMaxScaler()
df_minmax_scaled = df.copy()
df_minmax_scaled[num_features] = scaler_minmax.fit_transform(df[num_features])
df_minmax_scaled.pcp.unique()

array([0.00234742, 0.69014085, 0.60680751, 0.592723  , 0.44953052,
       0.45539906, 1.        , 0.36384977, 0.50704225, 0.31690141,
       0.36619718, 0.40492958, 0.29694836, 0.37910798, 0.23591549,
       0.29577465, 0.17018779, 0.15258216, 0.39201878, 0.23943662,
       0.12323944, 0.19248826, 0.19835681, 0.29812207, 0.35211268,
       0.13497653, 0.21830986, 0.44366197, 0.30046948, 0.13615023,
       0.27699531, 0.29929577, 0.11150235, 0.25704225, 0.17957746,
       0.24530516, 0.25586854, 0.21948357, 0.08215962, 0.14201878,
       0.25117371, 0.1056338 , 0.20657277, 0.20774648, 0.11502347,
       0.13849765, 0.12676056, 0.16197183, 0.16314554, 0.20422535,
       0.18192488, 0.13967136, 0.18661972, 0.21126761, 0.19953052,
       0.17840376, 0.19483568, 0.15375587, 0.17253521, 0.17723005,
       0.21596244, 0.17488263, 0.0786385 , 0.05751174, 0.16079812,
       0.18075117, 0.22065728, 0.05985915, 0.16901408, 0.24413146,
       0.12206573, 0.15023474, 0.04460094, 0.03521127, 0.24178404,
       0.15962441, 0.1314554 , 0.18309859, 0.07042254, 0.04694836,
       0.11267606, 0.10328638, 0.12910798, 0.10915493, 0.03873239,
       0.        , 0.68309859, 0.59741784, 0.59037559, 0.45305164,
       0.37089202, 0.51760563, 0.31103286, 0.35093897, 0.40023474,
       0.29460094, 0.24295775, 0.37323944, 0.28051643, 0.14788732,
       0.37441315, 0.11619718, 0.22535211, 0.18544601, 0.28873239,
       0.34741784, 0.22300469, 0.13380282, 0.41901408, 0.28755869,
       0.25938967, 0.13028169, 0.26995305, 0.28638498, 0.10211268,
       0.23826291, 0.25234742, 0.07629108, 0.20070423, 0.24882629,
       0.10446009, 0.20305164, 0.11032864, 0.13732394, 0.18779343,
       0.11384977, 0.19131455, 0.15140845, 0.19014085, 0.05868545,
       0.2100939 , 0.157277  , 0.16666667, 0.07276995, 0.06338028,
       0.17370892, 0.16549296, 0.12793427, 0.1971831 , 0.1584507 ,
       0.11971831, 0.04225352, 0.14671362, 0.02934272, 0.05399061,
       0.17605634, 0.03755869, 0.06455399, 0.0399061 , 0.07394366,
       0.09507042, 0.69600939, 0.61150235, 0.44835681, 0.58920188,
       0.45892019, 0.52230047, 0.36267606, 0.39788732, 0.38262911,
       0.15492958, 0.16431925, 0.38380282, 0.2370892 , 0.11737089,
       0.19600939, 0.48356808, 0.30164319, 0.26877934, 0.29342723,
       0.27112676, 0.27464789, 0.13262911, 0.16784038, 0.21244131,
       0.09741784, 0.22887324, 0.18896714, 0.48591549, 0.25      ,
       0.04342723, 0.07159624, 0.04812207, 0.14319249, 0.12558685,
       0.14084507, 0.70422535, 0.45070423, 0.59507042, 0.46478873,
       0.37206573, 0.54694836, 0.407277  , 0.38967136, 0.15610329,
       0.1185446 , 0.22652582, 0.49530516, 0.14906103, 0.27816901,
       0.26760563, 0.07981221, 0.08098592, 0.10680751, 0.1443662 ,
       0.12089202, 0.1842723 , 0.22183099, 0.49647887, 0.03638498,
       0.06807512, 0.19366197, 0.05633803, 0.0915493 , 0.05046948,
       0.10798122, 0.63849765, 0.46244131, 0.41431925, 0.58333333,
       0.30868545, 0.26056338, 0.27347418, 0.14553991, 0.23122066,
       0.21361502, 0.08920188, 0.26408451, 0.08333333, 0.20539906,
       0.09859155, 0.06103286, 0.04929577, 0.03169014, 0.49178404,
       0.0528169 , 0.05164319, 0.04577465, 0.09389671, 0.05516432,
       0.092723  , 0.12441315, 0.06924883, 0.65375587, 0.39671362,
       0.57394366, 0.43661972, 0.57981221, 0.28521127, 0.25469484,
       0.2241784 , 0.36737089, 0.08450704, 0.20187793, 0.25821596,
       0.10093897, 0.08685446, 0.06690141, 0.49765258, 0.1713615 ,
       0.09976526, 0.02347418, 0.0657277 , 0.08802817, 0.66079812,
       0.40375587, 0.5786385 , 0.43779343, 0.60446009, 0.28286385,
       0.24765258, 0.2629108 , 0.21478873, 0.36150235, 0.09624413,
       0.08568075, 0.03403756, 0.02699531, 0.47183099, 0.21713615,
       0.67723005, 0.41784038, 0.46830986, 0.45187793, 0.2899061 ,
       0.30985915, 0.09037559, 0.20892019, 0.51056338, 0.03286385,
       0.07511737, 0.7100939 , 0.43544601, 0.61384977, 0.48239437,
       0.4741784 , 0.62558685, 0.31338028, 0.33098592, 0.29225352,
       0.27230047, 0.23474178, 0.52816901, 0.23239437, 0.23004695,
       0.27934272, 0.72535211, 0.45774648, 0.62441315, 0.48943662,
       0.48122066, 0.65140845, 0.31924883, 0.33215962, 0.26525822,
       0.36971831, 0.29107981, 0.22769953, 0.04107981, 0.53638498])

In [46]:
scaler_std = StandardScaler()
df_std_scaled = df.copy()
df_std_scaled[num_features] = scaler_std.fit_transform(df[num_features])
df_std_scaled.pcp.unique()

array([-1.15814876e+00,  3.37907256e+00,  2.82934097e+00,  2.73642859e+00,
        1.79181937e+00,  1.83053286e+00,  5.42314497e+00,  1.22660238e+00,
        2.17121159e+00,  9.16894436e-01,  1.24208777e+00,  1.49759682e+00,
        7.85268562e-01,  1.32725746e+00,  3.82648239e-01,  7.77525863e-01,
       -5.09428774e-02, -1.67083355e-01,  1.41242714e+00,  4.05876335e-01,
       -3.60650818e-01,  9.61683943e-02,  1.34881887e-01,  7.93011260e-01,
        1.14917539e+00, -2.83223833e-01,  2.66507761e-01,  1.75310588e+00,
        8.08496657e-01, -2.75481134e-01,  6.53642687e-01,  8.00753959e-01,
       -4.38077803e-01,  5.22016812e-01,  1.09987107e-02,  4.44589827e-01,
        5.14274114e-01,  2.74250460e-01, -6.31645266e-01, -2.36767642e-01,
        4.83303320e-01, -4.76791295e-01,  1.89080776e-01,  1.96823475e-01,
       -4.14849707e-01, -2.59995737e-01, -3.37422722e-01, -1.05141767e-01,
       -9.73990684e-02,  1.73595379e-01,  2.64841077e-02, -2.52253039e-01,
        5.74549017e-02,  2.20051570e-01,  1.42624585e-01,  3.25601218e-03,
        1.11653791e-01, -1.59340656e-01, -3.54574804e-02, -4.48668633e-03,
        2.51022364e-01, -1.99720833e-02, -6.54873361e-01, -7.94241934e-01,
       -1.12884465e-01,  1.87414092e-02,  2.81993158e-01, -7.78756537e-01,
       -5.86855759e-02,  4.36847129e-01, -3.68393516e-01, -1.82568752e-01,
       -8.79411618e-01, -9.41353206e-01,  4.21361732e-01, -1.20627164e-01,
       -3.06451928e-01,  3.42268062e-02, -7.09072251e-01, -8.63926221e-01,
       -4.30335104e-01, -4.92276692e-01, -3.21937325e-01, -4.53563200e-01,
       -9.18125110e-01, -1.17363416e+00,  3.33261637e+00,  2.76739938e+00,
        2.72094319e+00,  1.81504746e+00,  1.27305857e+00,  2.24089588e+00,
        8.78180944e-01,  1.14143269e+00,  1.46662603e+00,  7.69783165e-01,
        4.29104430e-01,  1.28854396e+00,  6.76870782e-01, -1.98054149e-01,
        1.29628666e+00, -4.07107009e-01,  3.12963953e-01,  4.97122032e-02,
        7.31069672e-01,  1.11820460e+00,  2.97478556e-01, -2.90966531e-01,
        1.59050921e+00,  7.23326973e-01,  5.37502209e-01, -3.14194627e-01,
        6.07186496e-01,  7.15584275e-01, -5.00019391e-01,  3.98133636e-01,
        4.91046018e-01, -6.70358758e-01,  1.50367284e-01,  4.67817923e-01,
       -4.84533994e-01,  1.65852681e-01, -4.45820501e-01, -2.67738436e-01,
        6.51976002e-02, -4.22592406e-01,  8.84256958e-02, -1.74826054e-01,
        8.06829973e-02, -7.86499236e-01,  2.12308872e-01, -1.36112561e-01,
       -7.41709729e-02, -6.93586854e-01, -7.55528442e-01, -2.77147819e-02,
       -8.19136714e-02, -3.29680024e-01,  1.27139188e-01, -1.28369862e-01,
       -3.83878913e-01, -8.94897015e-01, -2.05796848e-01, -9.80066698e-01,
       -8.17470030e-01, -1.22293848e-02, -9.25867809e-01, -7.47785743e-01,
       -9.10382412e-01, -6.85844155e-01, -5.46475582e-01,  3.41778605e+00,
        2.86031176e+00,  1.78407667e+00,  2.71320049e+00,  1.85376096e+00,
        2.27186668e+00,  1.21885968e+00,  1.45114063e+00,  1.35048555e+00,
       -1.51597958e-01, -8.96563699e-02,  1.35822825e+00,  3.90390938e-01,
       -3.99364310e-01,  1.19396490e-01,  2.01635762e+00,  8.16239356e-01,
        5.99443797e-01,  7.62040466e-01,  6.14929194e-01,  6.38157290e-01,
       -2.98709230e-01, -6.64282744e-02,  2.27794269e-01, -5.30990185e-01,
        3.36192048e-01,  7.29402988e-02,  2.03184302e+00,  4.75560621e-01,
       -8.87154316e-01, -7.01329552e-01, -8.56183522e-01, -2.29024943e-01,
       -3.45165421e-01, -2.44510340e-01,  3.47198494e+00,  1.79956207e+00,
        2.75191398e+00,  1.89247445e+00,  1.28080127e+00,  2.43446334e+00,
        1.51308222e+00,  1.39694174e+00, -1.43855259e-01, -3.91621612e-01,
        3.20706651e-01,  2.09378461e+00, -1.90311451e-01,  6.61385385e-01,
        5.91701099e-01, -6.47130663e-01, -6.39387964e-01, -4.69048597e-01,
       -2.21282245e-01, -3.76136215e-01,  4.19695047e-02,  2.89735857e-01,
        2.10152731e+00, -9.33610507e-01, -7.24557648e-01,  1.03911093e-01,
       -8.01984633e-01, -5.69703677e-01, -8.40698125e-01, -4.61305898e-01,
        3.03839383e+00,  1.87698905e+00,  1.55953841e+00,  2.67448700e+00,
        8.62695547e-01,  5.45244908e-01,  6.30414591e-01, -2.13539546e-01,
        3.51677445e-01,  2.35536967e-01, -5.85189074e-01,  5.68473003e-01,
       -6.23902567e-01,  1.81338078e-01, -5.23247486e-01, -7.71013839e-01,
       -8.48440824e-01, -9.64581301e-01,  2.07055651e+00, -8.25212728e-01,
       -8.32955427e-01, -8.71668919e-01, -5.54218280e-01, -8.09727331e-01,
       -5.61960979e-01, -3.52908119e-01, -7.16814949e-01,  3.13904891e+00,
        1.44339793e+00,  2.61254541e+00,  1.70664968e+00,  2.65125890e+00,
        7.07841576e-01,  5.06531415e-01,  3.05221254e-01,  1.24983047e+00,
       -6.16159869e-01,  1.58109982e-01,  5.29759511e-01, -5.07762089e-01,
       -6.00674471e-01, -7.32300346e-01,  2.10927001e+00, -4.32001789e-02,
       -5.15504788e-01, -1.01878019e+00, -7.40043045e-01, -5.92931773e-01,
        3.18550510e+00,  1.48985413e+00,  2.64351620e+00,  1.71439238e+00,
        2.81385557e+00,  6.92356179e-01,  4.60075224e-01,  5.60730305e-01,
        2.43279666e-01,  1.21111698e+00, -5.38732883e-01, -6.08417170e-01,
       -9.49095904e-01, -9.95552095e-01,  1.93893064e+00,  2.58765063e-01,
        3.29390288e+00,  1.58276651e+00,  1.91570254e+00,  1.80730476e+00,
        7.38812370e-01,  8.70438245e-01, -5.77446376e-01,  2.04566173e-01,
        2.19443969e+00, -9.56838603e-01, -6.78101457e-01,  3.51069844e+00,
        1.69890699e+00,  2.87579716e+00,  2.00861493e+00,  1.95441604e+00,
        2.95322414e+00,  8.93666341e-01,  1.00980682e+00,  7.54297768e-01,
        6.22671893e-01,  3.74905541e-01,  2.31058017e+00,  3.59420144e-01,
        3.43934747e-01,  6.69128084e-01,  3.61135352e+00,  1.84601826e+00,
        2.94548145e+00,  2.05507112e+00,  2.00087223e+00,  3.12356351e+00,
        9.32379833e-01,  1.01754952e+00,  5.76215702e-01,  1.26531587e+00,
        7.46555069e-01,  3.28449350e-01, -9.02639713e-01,  2.36477906e+00])

Масштабируйте категориальные признаки через OneHotEncoder

In [50]:
from sklearn.preprocessing import OneHotEncoder

# Create an instance of OneHotEncoder
encoder = OneHotEncoder()
encoder_df = pd.DataFrame(encoder. fit_transform(df[['pcp']]). toarray ())
final_df = df.join (encoder_df)
print(final_df)

     world_rank                              university_name national_rank  \
0             1                           Harvard University             1
1             2                      University of Cambridge             1
2             3                          Stanford University             2
3             4           University of California, Berkeley             3
4             5  Massachusetts Institute of Technology (MIT)             4
...         ...                                          ...           ...
4492         96                          McMaster University             4
4493         97                           University of Bonn             4
4494         98                      VU University Amsterdam             4
4495         99                    Michigan State University            50
4496        100                         Texas A&M University            51

      total_score  alumni  award   hici     ns    pub   pcp  ...  310  311  \
0           100.0   100.0  100.0  100.0  100.0  100.0  15.0  ...  0.0  0.0
1            73.6    99.8   93.4   53.3   56.6   70.9  15.0  ...  0.0  0.0
2            73.4    41.1   72.2   88.5   70.9   72.3  15.0  ...  0.0  0.0
3            72.8    71.8   76.0   69.4   73.9   72.2  15.0  ...  0.0  0.0
4            70.1    74.0   80.6   66.7   65.8   64.3  15.0  ...  0.0  0.0
...           ...     ...    ...    ...    ...    ...   ...  ...  ...  ...
4492         24.4    12.6   18.8   23.2   15.1   44.5  22.5  ...  NaN  NaN
4493         24.3    15.4   19.8   17.4   21.1   39.8  25.9  ...  NaN  NaN
4494         24.2     0.0    0.0   27.8   18.0   55.5  33.3  ...  NaN  NaN
4495         24.0     8.9    0.0   30.7   21.8   50.6  18.9  ...  NaN  NaN
4496         23.9     0.0    0.0   34.3   22.7   49.5  20.9  ...  NaN  NaN

      312  313  314  315  316  317  318  319
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...
4492  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4493  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4494  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4495  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4496  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[1101 rows x 331 columns]

##Задание для гениев*


Реализовать расчет корреляции Спирмана

In [ ]:
#Функция по расчету тут

In [ ]:
#Пример использования тут и объяснение принципа работы

###Пример реализации

In [ ]:
import pandas as pd
import numpy as np


def corr_pearson(column_1, column_2):
  cov = np.cov(column_1, column_2)
  return cov/(column_1.std() * column_2.std())

In [ ]:
data = {
    'Рост': [170, 155, 180, 162, 175],
    'Вес': [65, 50, 75, 55, 70]
}
df = pd.DataFrame(data)
df

   Рост  Вес
0   170   65
1   155   50
2   180   75
3   162   55
4   175   70

In [ ]:
corr_pearson(df["Рост"], df["Вес"])

array([[0.96593129, 0.99674864],
       [0.99674864, 1.03527033]])